servers:
  - url: nats://nats1.plugis.com:443
    sni:  true

postgres:
  database: plugis
  user:     plugis
  password: plugis
  port:     5432

mysql:
  database: plugis
  user:     plugis
  password: plugis
  port:     3306
