### Send POST request with json body
POST http://localhost:8080/cloudevents/send
Content-Type: application/json

{
  "topic": "com.plugis.shell.B8:27:EB:E7:B3:4E",
  "request": true,
  "data": {"command": ["df","-lh","/"]},
  "source": "web",
  "specversion": "1.0",
  "type": "com.plugis.shell.command"
}
